name: PeoplePurposeImpact
favicon: null
layout_spectrum: 0.49876
typography_spectrum: 0.603891302831471
title: PeoplePurposeImpact
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#505050'
    - '#ff0000'
    - '#ffffff'
    - '#ff9b97'
    - '#ff5550'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.029344406677410007
purpose: []
