name: PeoplePurposeImpact
favicon: null
layout_spectrum: 0.6413629564922303
typography_spectrum: 0.603891302831471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9116149742621928
  lightness: 0.9417885218281299
  saturation: 0.5411784341558814
  rhythmicContrast: 0.029344406677410007
purpose: []
